config/routes.rb
Rails.application.routes.draw do
  resources :scorecards

  root 'scorecards#new'

end

app/models/batting.rb
class Batting < ActiveRecord::Base
  belongs_to :scorecard
  scope :first_inning, -> {where(batting_no: 1)}
  scope :second_inning, -> {where(batting_no: 2)}
end

app/models/bowling.rb
class Bowling < ActiveRecord::Base
  belongs_to :scorecard
  scope :first_inning, -> {where(bowling_no: 1)}
  scope :second_inning, -> {where(bowling_no: 2)}

end

app/models/scorecard.rb
class Scorecard < ActiveRecord::Base
	has_many :battings, dependent: :destroy
	has_many :bowlings, dependent: :destroy
	validates :url, presence: true
	validates :url, :format => URI::regexp(%w(http https))
	after_create :build_battings
	after_create :build_bowlings
	private
		def build_battings
			page_data = Crawlar.new(self.url)
			page_data.get_batting_card.each do |batsman|
				self.battings.create!( name: batsman[0], status: batsman[1], runs: batsman[2], 
														 	 balls: batsman[3], fours: batsman[4], sixes: batsman[5],
														 	 strik_rake: batsman[6], batting_no: 1)
			end
			page_data.get_second_batting_card.each do |batsman|
				self.battings.create!( name: batsman[0], status: batsman[1], runs: batsman[2], 
														 	 balls: batsman[3], fours: batsman[4], sixes: batsman[5],
														 	 strik_rake: batsman[6], batting_no: 2)
			end
		end

		def build_bowlings
			page_data = Crawlar.new(self.url)
			page_data.get_first_bowling.each do |bowlar|
				self.bowlings.create!( name: bowlar[0], overs: bowlar[1], maidens: bowlar[2], 
														 	 runs: bowlar[3], wickets: bowlar[4], economy: bowlar[5],
															 bowling_no: 1
															)
			end

			page_data.get_second_bowling.each do |bowlar|
				self.bowlings.create!( name: bowlar[0], overs: bowlar[1], maidens: bowlar[2], 
														 	 runs: bowlar[3], wickets: bowlar[4], economy: bowlar[5],
															 bowling_no: 2
															)
			end

		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/scorecards_controller.rb
class ScorecardsController < ApplicationController
  before_action :set_scorecard, only: [:show, :edit, :update, :destroy]

  # GET /scorecards
  # GET /scorecards.json
  def index
    @scorecards = Scorecard.all
  end

  # GET /scorecards/1
  # GET /scorecards/1.json
  def show
  end

  # GET /scorecards/new
  def new
    @scorecard = Scorecard.new
  end

  # GET /scorecards/1/edit
  def edit
  end

  # POST /scorecards
  # POST /scorecards.json
  def create
    @scorecard = Scorecard.new(scorecard_params)

    respond_to do |format|
      if @scorecard.save
        format.html { redirect_to @scorecard, notice: 'Scorecard was successfully created.' }
        format.json { render :show, status: :created, location: @scorecard }
      else
        format.html { render :new }
        format.json { render json: @scorecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scorecards/1
  # PATCH/PUT /scorecards/1.json
  def update
    respond_to do |format|
      if @scorecard.update(scorecard_params)
        format.html { redirect_to @scorecard, notice: 'Scorecard was successfully updated.' }
        format.json { render :show, status: :ok, location: @scorecard }
      else
        format.html { render :edit }
        format.json { render json: @scorecard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scorecards/1
  # DELETE /scorecards/1.json
  def destroy
    @scorecard.destroy
    respond_to do |format|
      format.html { redirect_to scorecards_url, notice: 'Scorecard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scorecard
      @scorecard = Scorecard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scorecard_params
      params.require(:scorecard).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scorecards_helper.rb
module ScorecardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Espn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/scorecards/_batsman.html.erb
_batsman.html.erb

app/views/scorecards/_form.html.erb
<%= form_for(@scorecard) do |f| %>
  <% if @scorecard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scorecard.errors.count, "error") %> prohibited this scorecard from being saved:</h2>

      <ul>
      <% @scorecard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scorecards/edit.html.erb
<h1>Editing Scorecard</h1>

<%= render 'form' %>

<%= link_to 'Show', @scorecard %> |
<%= link_to 'Back', scorecards_path %>

app/views/scorecards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scorecards</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scorecards.each do |scorecard| %>
      <tr>
        <td><%= scorecard.url %></td>
        <td><%= link_to 'Show', scorecard %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scorecard', new_scorecard_path %>

app/views/scorecards/new.html.erb
<h1>New Scorecard</h1>

<%= render 'form' %>

<%= link_to 'Back', scorecards_path %>

app/views/scorecards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @scorecard.url %>
</p>
<div class="bs-example" data-example-id="condensed-table"> 
	<table class="table table-condensed">
	<thead> <tr> <th>Name</th> <th>status</th> <th>Runs</th> <th>Balls</th><th>fours</th><th>sixes</th><th>strik rate</th> </tr> </thead> 
		<tbody>  
			<% @scorecard.battings.first_inning.each do |batting| %>
			<tr>
				<th><%= batting.name %></th><td><%= batting.status %></td><td><%= batting.runs %></td><td><%= batting.balls %></td><td><%= batting.fours %></td><td><%= batting.sixes %></td><td><%= batting.strik_rake %></td>
			</tr>
			<% end %>
		</tbody> 
	</table> 
</div>
<h2>Bowling</h2>
<div class="bs-example" data-example-id="condensed-table"> 
	<table class="table table-condensed">
	<thead> <tr> <th>Name</th> <th>overs</th> <th>Maidens</th><th>Runs</th><th>Wickets</th><th>Economy</th> </tr> </thead> 
		<tbody>  
			<% @scorecard.bowlings.first_inning.each do |bowling| %>
			<tr>
				<th><%= bowling.name %></th><td><%= bowling.overs %></td><td><%= bowling.maidens %></td><td><%= bowling.runs %></td><td><%= bowling.wickets %></td><td><%= bowling.economy %></td>
			</tr>
			<% end %>
		</tbody> 
	</table> 
</div>

<h2>Batting</h2>
<div class="bs-example" data-example-id="condensed-table"> 
	<table class="table table-condensed">
	<thead> <tr> <th>Name</th> <th>status</th> <th>Runs</th> <th>Balls</th><th>fours</th><th>sixes</th><th>strik rate</th> </tr> </thead> 
		<tbody>  
			<% @scorecard.battings.second_inning.each do |batting| %>
			<tr>
				<th><%= batting.name %></th><td><%= batting.status %></td><td><%= batting.runs %></td><td><%= batting.balls %></td><td><%= batting.fours %></td><td><%= batting.sixes %></td><td><%= batting.strik_rake %></td>
			</tr>
			<% end %>
		</tbody> 
	</table> 
</div>
<h2>Bowling</h2>
<div class="bs-example" data-example-id="condensed-table"> 
	<table class="table table-condensed">
	<thead> <tr> <th>Name</th> <th>overs</th> <th>Maidens</th><th>Runs</th><th>Wickets</th><th>Economy</th> </tr> </thead> 
		<tbody>  
			<% @scorecard.bowlings.second_inning.each do |bowling| %>
			<tr>
				<th><%= bowling.name %></th><td><%= bowling.overs %></td><td><%= bowling.maidens %></td><td><%= bowling.runs %></td><td><%= bowling.wickets %></td><td><%= bowling.economy %></td>
			</tr>
			<% end %>
		</tbody> 
	</table> 
</div>